name: GithubActions_Final
on: 
  push:
   branches:
    - master
jobs:
  Linter_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -D
      - run: npm run lint
  
  Cypress_job:
    needs: Linter_job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v5
        with:
          config-file: cypress.json
          build: npm run build
          start: npm start
        id: cypress
        continue-on-error: true
      - run: echo ${{ steps.cypress.outcome }}  > result.txt
      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: ./result.txt

  Add_badge_job:
    needs: Cypress_job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: result
      - run: echo "::set-output name=cypress_outcome::$(cat result.txt)"
        id: results
      - uses: ./.github/actions/changereadme
        env:
          resultado: ${{ steps.results.outputs.cypress_outcome }}
      - uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: "Santi Martinez Albert"
          author_email: "santimartinezalbert02@gmail.com"
          message: "Readme Updated succesfully"
          push: true
  
  Deploy_job:
    needs: Cypress_job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: ./

  Notification_job:
    needs: [Cypress_job, Add_badge_job, Linter_job, Deploy_job]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sendMail
        env:
          API_KEY: ${{secrets.MAILGUN_APIKEY}}
          DOMAIN: ${{secrets.MAILGUN_DOMAIN}}
          destinatario: ${{secrets.destinatario}}
          linter_job: ${{needs.Cypress_job.result}}
          cypress_job: ${{needs.Cypress_job.result}}
          add_badge_job: ${{needs.Add_badge_job.result}}
          deploy_job: ${{needs.Deploy_job.result}}